const x = {
  valid: true,
  redeemables: [
    {
      status: 'APPLICABLE',
      id: 'promo_IqO1UhFoBLatVBg80rGuo7gt',
      object: 'promotion_tier',
      order: {
        source_id: '659bd1c5185dd93c73e9993d',
        amount: 79323,
        discount_amount: 0,
        items_discount_amount: 7313,
        total_discount_amount: 7313,
        total_amount: 72010,
        items_applied_discount_amount: 7313,
        total_applied_discount_amount: 7313,
        items: [
          {
            object: 'order_item',
            source_id: '21349812',
            related_object: 'product',
            quantity: 1,
            amount: 29253,
            discount_amount: 7313,
            applied_discount_amount: 7313,
            price: 29253,
            subtotal_amount: 21940,
            product: {
              id: 'prod_0d3571906081731ed0',
              source_id: '21349812',
              name: 'Lenovo IdeaTab A2107',
              override: true,
            },
            sku: {
              metadata: {},
              override: true,
            },
          },
          {
            object: 'order_item',
            source_id: '3549904',
            related_object: 'product',
            quantity: 1,
            amount: 25343,
            price: 25343,
            subtotal_amount: 25343,
            product: {
              id: 'prod_0d35859bbb8173555d',
              source_id: '3549904',
              name: 'Sony PlayStation 5 Digital Edition',
              override: true,
            },
            sku: {
              metadata: {},
              override: true,
            },
          },
          {
            object: 'order_item',
            source_id: '19846329',
            related_object: 'product',
            quantity: 1,
            amount: 24727,
            price: 24727,
            subtotal_amount: 24727,
            product: {
              id: 'prod_0d3571803601731e1c',
              source_id: '19846329',
              name: 'Sony DualShock 4',
              override: true,
            },
            sku: {
              metadata: {},
              override: true,
            },
          },
        ],
        metadata: {
          currentLanguage: 'en',
          activeCurrency: 'USD',
          preferredCurrency: 'EUR',
          preferredLanguage: 'en_US',
        },
        customer_id: null,
        referrer_id: null,
        object: 'order',
      },
      applicable_to: {
        data: [
          {
            object: 'products_collection',
            id: 'pc_3ASVNbZirZMCmTRp2BlS1ojt',
            strict: false,
            effect: 'APPLY_TO_EVERY',
            order_item_indices: [0],
          },
          {
            object: 'product',
            id: 'prod_0d3571906081731ed0',
            source_id: '21349812',
            strict: true,
            effect: 'APPLY_TO_EVERY',
            order_item_indices: [0],
          },
        ],
        total: 2,
        data_ref: 'data',
        object: 'list',
      },
      inapplicable_to: {
        data: [],
        total: 0,
        data_ref: 'data',
        object: 'list',
      },
      result: {
        discount: {
          type: 'PERCENT',
          effect: 'APPLY_TO_ITEMS',
          percent_off: 25,
          is_dynamic: false,
        },
      },
    },
  ],
  order: {
    source_id: '659bd1c5185dd93c73e9993d',
    amount: 79323,
    discount_amount: 0,
    items_discount_amount: 7313,
    total_discount_amount: 7313,
    total_amount: 72010,
    items_applied_discount_amount: 7313,
    total_applied_discount_amount: 7313,
    items: [
      {
        object: 'order_item',
        source_id: '21349812',
        related_object: 'product',
        quantity: 1,
        amount: 29253,
        discount_amount: 7313,
        applied_discount_amount: 7313,
        price: 29253,
        subtotal_amount: 21940,
        product: {
          id: 'prod_0d3571906081731ed0',
          source_id: '21349812',
          name: 'Lenovo IdeaTab A2107',
          override: true,
        },
        sku: {
          metadata: {},
          override: true,
        },
      },
      {
        object: 'order_item',
        source_id: '3549904',
        related_object: 'product',
        quantity: 1,
        amount: 25343,
        price: 25343,
        subtotal_amount: 25343,
        product: {
          id: 'prod_0d35859bbb8173555d',
          source_id: '3549904',
          name: 'Sony PlayStation 5 Digital Edition',
          override: true,
        },
        sku: {
          metadata: {},
          override: true,
        },
      },
      {
        object: 'order_item',
        source_id: '19846329',
        related_object: 'product',
        quantity: 1,
        amount: 24727,
        price: 24727,
        subtotal_amount: 24727,
        product: {
          id: 'prod_0d3571803601731e1c',
          source_id: '19846329',
          name: 'Sony DualShock 4',
          override: true,
        },
        sku: {
          metadata: {},
          override: true,
        },
      },
    ],
    metadata: {
      currentLanguage: 'en',
      activeCurrency: 'USD',
      preferredCurrency: 'EUR',
      preferredLanguage: 'en_US',
    },
    customer_id: null,
    referrer_id: null,
    object: 'order',
  },
  tracking_id: 'track_/rrG5nR18+LseUXGzA1vtMqbh1pLKLwB',
  session: {
    key: 'ssn_f39NJ7t0aqlWqbjj4TZiViH8O7gLZZ0h',
    type: 'LOCK',
    ttl: 7,
    ttl_unit: 'DAYS',
  },
}
